
tasks:
  - name: Go prep
    init: |
      go get ./...
      go build -o zeno main.go
      rm -rf zeno
  - name: Earthly install
    before: |
      sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
      sudo chmod +x /usr/local/bin/earthly
      sudo /usr/local/bin/earthly bootstrap --with-autocomplete
  - name: Install flyctl
    before: |
      curl -L https://fly.io/install.sh | sh
      echo "export PATH=/home/gitpod/.fly/bin:$PATH" >> ~/.bash_profile
  - name: Install serve
    before: npm install --global serve -y

vscode:
  extensions:
    - golang.go
    - eamodio.gitlens
