
tasks:
  - name: Go prep
    init: |
      go get ./...
      go build -o zeno main.go
      rm -rf zeno
  - name: Install flyctl
    before: |
      curl -L https://fly.io/install.sh | sh
      echo "export PATH=/home/gitpod/.fly/bin:$PATH" >> ~/.bash_profile
  - name: Install serve
    before: npm install --global serve -y
  - name: Install Meili
    before: curl -L https://install.meilisearch.com | sh
  - name: Install pdftotext
    before: sudo apt-get install poppler-utils -y
  - name: Install Just
    before: cargo install just

vscode:
  extensions:
    - golang.go
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
